env: "dev" #dev, prod
token_ttl: 1h
db:
  host: "localhost"
  port: 5432
  user: "alonmell"
  password: "zasode"
  database: "ProviderHub"
http_server:
  address: "localhost:8080"
  timeout: 5s
  idle_timeout: 60s
