env: "dev" #dev, prod
db:
  host: "localhost"
  port: 5432
  user: "alonmell"
  password: "zasode"
  database: "ProviderHub"
http_server:
  address: "localhost:8080"
  timeout: 5s
  idle_timeout: 60s
jwt:
  access_ttl: 15m
  refresh_ttl: 168h
  secret: "secretsecretsecretsecretsecret"