env: "dev" #dev, prod
token_ttl: 1h
db:
  host: "localhost"
  port: 5432
  user: "alonmell"
  password: "zasode"
  database: "ProviderHub"
migrations:
    #major, minor: 0,  0 -> baseline
    major_version: 0
    minor_version: 0
    sql_path: "./internal/storage/postgres/sql/"
    table_name: "migrations_history"
http_server:
  address: "localhost:8082"
  timeout: 5s
  idle_timeout: 60s
